$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: power-gen-model-training
description: Training Pipeline to train a model that predicts taxi fare price

# <inputs_and_outputs>
inputs:
  input:
    type: uri_file
    path: azureml:power-gen-data@latest

#outputs: 
#  evaluation_output:
# </inputs_and_outputs>

# <jobs>
settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cluster
  continue_on_step_failure: false

jobs:
  train_data:
    name: train_data
    display_name: prep-data
    code: src
    command: >-
      python training.py 
      --raw_data ${{inputs.raw_data}} 
      --model_name ${{inputs.model_name}}
#      --evaluation_output ${{inputs.evaluation_output}}
    environment: azureml:power-gen-train-env:3
    inputs:
      raw_data: ${{parent.inputs.input}}
      model_name: "power-gen-model"
#    outputs:
#      evaluation_output: ${{parent.outputs.evaluation_output}}
# </jobs>
